### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by jordan8037310** [pantheon-systems/terminus-quicksilver-plugin#1]
$ composer global install pantheon-systems/quicksilver-cli
Changed current directory to /Users/jordanryan/.composer
Invalid argument pantheon-systems/quicksilver-cli. Use "composer require pantheon-systems/quicksilver-cli" instead to add packages to your composer.json.

**Comment by jordan8037310** [comment]
When running composer require, there are conflicts in the build:

composer require pantheon-systems/quicksilver-cli
Using version ^0.1.0 for pantheon-systems/quicksilver-cli
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pantheon-systems/quicksilver-cli 0.1.0 requires stecman/symfony-console-completion ^0.5.1 -> satisfiable by stecman/symfony-console-completion[0.5.1].
    - Installation request for pantheon-systems/quicksilver-cli ^0.1.0 -> satisfiable by pantheon-systems/quicksilver-cli[0.1.0].
    - Conclusion: remove symfony/console v3.0.1
    - Conclusion: don't install symfony/console v3.0.1
    - stecman/symfony-console-completion 0.5.1 requires symfony/console ~2.2 -> satisfiable by symfony/console[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - Can only install one of: symfony/console[v2.3.10, v3.0.1].
    - Can only install one of: symfony/console[v2.3.11, v3.0.1].
    - Can only install one of: symfony/console[v2.3.12, v3.0.1].
    - Can only install one of: symfony/console[v2.3.13, v3.0.1].
    - Can only install one of: symfony/console[v2.3.14, v3.0.1].
    - Can only install one of: symfony/console[v2.3.15, v3.0.1].
    - Can only install one of: symfony/console[v2.3.16, v3.0.1].
    - Can only install one of: symfony/console[v2.3.17, v3.0.1].
    - Can only install one of: symfony/console[v2.3.18, v3.0.1].
    - Can only install one of: symfony/console[v2.3.19, v3.0.1].
    - Can only install one of: symfony/console[v2.3.20, v3.0.1].
    - Can only install one of: symfony/console[v2.3.21, v3.0.1].
    - Can only install one of: symfony/console[v2.3.22, v3.0.1].
    - Can only install one of: symfony/console[v2.3.23, v3.0.1].
    - Can only install one of: symfony/console[v2.3.24, v3.0.1].
    - Can only install one of: symfony/console[v2.3.25, v3.0.1].
    - Can only install one of: symfony/console[v2.3.26, v3.0.1].
    - Can only install one of: symfony/console[v2.3.27, v3.0.1].
    - Can only install one of: symfony/console[v2.3.28, v3.0.1].
    - Can only install one of: symfony/console[v2.3.29, v3.0.1].
    - Can only install one of: symfony/console[v2.3.30, v3.0.1].
    - Can only install one of: symfony/console[v2.3.31, v3.0.1].
    - Can only install one of: symfony/console[v2.3.32, v3.0.1].
    - Can only install one of: symfony/console[v2.3.33, v3.0.1].
    - Can only install one of: symfony/console[v2.3.34, v3.0.1].
    - Can only install one of: symfony/console[v2.3.35, v3.0.1].
    - Can only install one of: symfony/console[v2.3.36, v3.0.1].
    - Can only install one of: symfony/console[v2.3.37, v3.0.1].
    - Can only install one of: symfony/console[v2.4.10, v3.0.1].
    - Can only install one of: symfony/console[v2.4.2, v3.0.1].
    - Can only install one of: symfony/console[v2.4.3, v3.0.1].
    - Can only install one of: symfony/console[v2.4.4, v3.0.1].
    - Can only install one of: symfony/console[v2.4.5, v3.0.1].
    - Can only install one of: symfony/console[v2.4.6, v3.0.1].
    - Can only install one of: symfony/console[v2.4.7, v3.0.1].
    - Can only install one of: symfony/console[v2.4.8, v3.0.1].
    - Can only install one of: symfony/console[v2.4.9, v3.0.1].
    - Can only install one of: symfony/console[v2.5.0, v3.0.1].
    - Can only install one of: symfony/console[v2.5.1, v3.0.1].
    - Can only install one of: symfony/console[v2.5.10, v3.0.1].
    - Can only install one of: symfony/console[v2.5.11, v3.0.1].
    - Can only install one of: symfony/console[v2.5.12, v3.0.1].
    - Can only install one of: symfony/console[v2.5.2, v3.0.1].
    - Can only install one of: symfony/console[v2.5.3, v3.0.1].
    - Can only install one of: symfony/console[v2.5.4, v3.0.1].
    - Can only install one of: symfony/console[v2.5.5, v3.0.1].
    - Can only install one of: symfony/console[v2.5.6, v3.0.1].
    - Can only install one of: symfony/console[v2.5.7, v3.0.1].
    - Can only install one of: symfony/console[v2.5.8, v3.0.1].
    - Can only install one of: symfony/console[v2.5.9, v3.0.1].
    - Can only install one of: symfony/console[v2.6.0, v3.0.1].
    - Can only install one of: symfony/console[v2.6.1, v3.0.1].
    - Can only install one of: symfony/console[v2.6.10, v3.0.1].
    - Can only install one of: symfony/console[v2.6.11, v3.0.1].
    - Can only install one of: symfony/console[v2.6.12, v3.0.1].
    - Can only install one of: symfony/console[v2.6.13, v3.0.1].
    - Can only install one of: symfony/console[v2.6.2, v3.0.1].
    - Can only install one of: symfony/console[v2.6.3, v3.0.1].
    - Can only install one of: symfony/console[v2.6.4, v3.0.1].
    - Can only install one of: symfony/console[v2.6.5, v3.0.1].
    - Can only install one of: symfony/console[v2.6.6, v3.0.1].
    - Can only install one of: symfony/console[v2.6.7, v3.0.1].
    - Can only install one of: symfony/console[v2.6.8, v3.0.1].
    - Can only install one of: symfony/console[v2.6.9, v3.0.1].
    - Can only install one of: symfony/console[v2.7.0, v3.0.1].
    - Can only install one of: symfony/console[v2.7.1, v3.0.1].
    - Can only install one of: symfony/console[v2.7.2, v3.0.1].
    - Can only install one of: symfony/console[v2.7.3, v3.0.1].
    - Can only install one of: symfony/console[v2.7.4, v3.0.1].
    - Can only install one of: symfony/console[v2.7.5, v3.0.1].
    - Can only install one of: symfony/console[v2.7.6, v3.0.1].
    - Can only install one of: symfony/console[v2.7.7, v3.0.1].
    - Can only install one of: symfony/console[v2.7.8, v3.0.1].
    - Can only install one of: symfony/console[v2.7.9, v3.0.1].
    - Can only install one of: symfony/console[v2.8.0, v3.0.1].
    - Can only install one of: symfony/console[v2.8.1, v3.0.1].
    - Can only install one of: symfony/console[v2.8.2, v3.0.1].
    - Can only install one of: symfony/console[v2.2.0, v3.0.1].
    - Can only install one of: symfony/console[v2.2.1, v3.0.1].
    - Can only install one of: symfony/console[v2.2.10, v3.0.1].
    - Can only install one of: symfony/console[v2.2.11, v3.0.1].
    - Can only install one of: symfony/console[v2.2.2, v3.0.1].
    - Can only install one of: symfony/console[v2.2.3, v3.0.1].
    - Can only install one of: symfony/console[v2.2.4, v3.0.1].
    - Can only install one of: symfony/console[v2.2.5, v3.0.1].
    - Can only install one of: symfony/console[v2.2.6, v3.0.1].
    - Can only install one of: symfony/console[v2.2.7, v3.0.1].
    - Can only install one of: symfony/console[v2.2.8, v3.0.1].
    - Can only install one of: symfony/console[v2.2.9, v3.0.1].
    - Can only install one of: symfony/console[v2.3.0, v3.0.1].
    - Can only install one of: symfony/console[v2.3.1, v3.0.1].
    - Can only install one of: symfony/console[v2.3.2, v3.0.1].
    - Can only install one of: symfony/console[v2.3.3, v3.0.1].
    - Can only install one of: symfony/console[v2.3.4, v3.0.1].
    - Can only install one of: symfony/console[v2.3.5, v3.0.1].
    - Can only install one of: symfony/console[v2.3.6, v3.0.1].
    - Can only install one of: symfony/console[v2.3.7, v3.0.1].
    - Can only install one of: symfony/console[v2.3.8, v3.0.1].
    - Can only install one of: symfony/console[v2.3.9, v3.0.1].
    - Can only install one of: symfony/console[v2.4.0, v3.0.1].
    - Can only install one of: symfony/console[v2.4.1, v3.0.1].
    - Installation request for symfony/console == 3.0.1.0 -> satisfiable by symfony/console[v3.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by ttrowell** [comment]
confirmed that the command required is `composer require pantheon-systems/quicksilver-cli`

Build did not fail on MAC OS El Capitan:

`Taras-MacBook-Pro:~ tararowell$ composer require pantheon-systems/quicksilver-cli
Using version ~1.0 for pantheon-systems/quicksilver-cli
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing composer/installers (v1.0.22)
  Downloading: 100%         
- Installing padraic/humbug_get_contents (1.0.4)
  Downloading: 100%         
- Installing padraic/phar-updater (1.0.3)
  Downloading: 100%         
- Installing symfony/finder (v2.7.9)
  Downloading: 100%         
- Installing guzzlehttp/promises (1.0.3)
  Downloading: 100%         
- Installing psr/http-message (1.0)
  Downloading: 100%         
- Installing guzzlehttp/psr7 (1.2.1)
  Downloading: 100%         
- Installing guzzlehttp/guzzle (6.1.1)
  Downloading: 100%         
- Installing symfony/polyfill-mbstring (v1.0.1)
  Downloading: 100%         
- Installing symfony/console (v2.7.9)
  Downloading: 100%         
- Installing stecman/symfony-console-completion (0.5.1)
  Downloading: 100%         
- Installing phpseclib/phpseclib (2.0.1)
  Downloading: 100%         
- Installing symfony/dom-crawler (v2.7.9)
  Downloading: 100%         
- Installing twig/twig (v1.23.3)
  Downloading: 100%         
- Installing symfony/yaml (v2.7.9)
  Downloading: 100%         
- Installing symfony/translation (v2.7.9)
  Downloading: 100%         
- Installing symfony/http-foundation (v2.7.9)
  Downloading: 100%         
- Installing symfony/filesystem (v2.7.9)
  Downloading: 100%         
- Installing symfony/event-dispatcher (v2.7.9)
  Downloading: 100%         
- Installing psr/log (1.0.0)
  Loading from cache
- Installing symfony/debug (v2.7.9)
  Downloading: 100%         
- Installing symfony/dependency-injection (v2.7.9)
  Downloading: 100%         
- Installing symfony/css-selector (v2.7.9)
  Downloading: 100%         
- Installing symfony/config (v2.7.9)
  Downloading: 100%         
- Installing henrikbjorn/lurker (1.0.0)
  Downloading: 100%         
- Installing symfony/process (v2.7.9)
  Downloading: 100%         
- Installing codegyre/robo (0.6.0)
  Downloading: 100%         
- Installing vlucas/phpdotenv (v2.1.1)
  Downloading: 100%         
- Installing rmccue/requests (v1.6.1)
  Downloading: 100%         
- Installing ramsey/array_column (1.1.3)
  Downloading: 100%         
- Installing jakub-onderka/php-console-color (0.1)
  Downloading: 100%         
- Installing jakub-onderka/php-console-highlighter (v0.3.2)
  Downloading: 100%         
- Installing dnoegel/php-xdg-base-dir (0.1)
  Downloading: 100%         
- Installing nikic/php-parser (v2.0.0)
  Downloading: 100%         
- Installing symfony/var-dumper (v3.0.1)
  Downloading: 100%         
- Installing psy/psysh (v0.6.1)
  Downloading: 100%         
- Installing katzgrau/klogger (1.2.0)
  Downloading: 100%         
- Installing jlogsdon/cli (v0.9.4-patch46)
  Downloading: 100%         
- Installing nb/oxymel (v0.1.0)
  Downloading: 100%         
- Installing pantheon-systems/cli (0.10.0)
  Downloading: 100%         
- Installing pantheon-systems/quicksilver-cli (1.0.0)
  Downloading: 100%  
  Downloading: 100%         

phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other cryptographic operations.)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
henrikbjorn/lurker suggests installing ext-inotify (>=0.1.6)
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
Writing lock file
Generating autoload files`

**Comment by allenfear** [comment]
`composer global require pantheon-systems/quicksilver-cli` failed for me too with the same error as above. 
`composer require pantheon-systems/quicksilver-cli` completed successfully.

**Comment by greg-1-anderson** [comment]
`composer global require` is a request for dependency hell and other forms of pain and suffering. This command may work or fail, depending on what other projects you have installed via `composer global require`.

This tool is being ported to a terminus plugin, so it will become easier to install and use.

**Comment by greg-1-anderson** [comment]
This tool has been converted to a Terminus plugin, so this should not be an issue any longer.
